version: '3'

services:
  ws_app:
    env_file:
      - .env
    container_name: ws_app
    build:
      context: .
      dockerfile: Dockerfile.loc
      args:
        user: laraveluser
        uid: 1000
    ports:
      - "8002:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=mysql2
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE} 
      - DB_USERNAME=${DB_USERNAME}  
      - DB_PASSWORD=${DB_PASSWORD} 
      ############################################
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - APP_URL=http://localhost:8003
      - APP_ENV=production
      - LOG_CHANNEL=stderr
      - LOG_LEVEL=info
      - LOG_STDERR_FORMATTER=Monolog\Formatter\JsonFormatter
      - SESSION_DRIVER=cookie
      - SESSION_SECURE_COOKIE=true
      - DB_CONNECTION=mysql
      - URL_WAREHOUSE_INGREDIENTS_SERVICE=https://warehouse-ingredients-service.fly.dev/
      - URL_MARKER_INGREDIENTS_SERVICE=https://farmers-market-service.fly.dev/
      - APP_TIMEZONE=America/Bogota
    command: bash -c "php artisan key:generate && php artisan migrate --force && apache2-foreground"
    networks:
      - my_network

networks:
  my_network:
    external:
      name: my_network