<?php

return [
    'URL_BUY_INGREDIENTS_SERVICE' => env('URL_BUY_INGREDIENTS_SERVICE'),
    'URL_ORDER_INGREDIENTS_SERVICE'=>env('URL_ORDER_INGREDIENTS_SERVICE'),
    'EMAIL_SYSTEM' => env('EMAIL_SYSTEM'),
    'PASS_SYSTEM' =>env('PASS_SYSTEM')
];
